/* import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
 */

import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar"; // 👈 Uvozi tvoj moderni Navbar
import Footer from "@/components/Footer";

// 1. Postavljanje luksuznih Google Fontova (Playfair za naslove, Inter za tekst)
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif", // Povezujemo sa Tailwind font-serif klasom
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// 2. SEO Metapodaci (Zamjena za React Helmet)
export const metadata = {
  title: {
    default: "Mina HM | Unikatna Krojačka Umjetnost",
    template: "%s | Mina HM", // Automatski dodaje "| Mina HM" na kraj svakog podnaslova stranice!
  },
  description: "Ekskluzivno šivenje po mjeri, unikatni radovi i krojački atelier koji odiše elegancijom.",
  keywords: ["krojačica", "šivenje po mjeri", "unikatna odjeća", "Mina HM", "dizajn"],
  metadataBase: new URL("https://mina-hm.com"),
  openGraph: {
    title: "Mina HM | Unikatna Krojačka Umjetnost",
    description: "Šivenje po mjeri i unikatni radovi krojeni za vas.",
    url: "https://mina-hm.com",
    siteName: "Mina HM",
    locale: "bs_BA",
    type: "website",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="bs" className={`${playfair.variable} ${inter.variable}`}>
      <body className="bg-[#faf9f6] text-slate-900 font-sans antialiased min-h-screen flex flex-col">
        
        {/* Navbar se prikazuje na SVIM stranicama automatski */}
        <NavBar />

        {/* Ovdje se učitava sadržaj pojedinačnih stranica (page.js) */}
        <main className="flex-grow">
          {children}
        </main>

        {/* Footer se prikazuje na SVIM stranicama automatski */}
        <Footer />
        
      </body>
    </html>
  );
}