name: Supabase Keep Alive

on:
  schedule:
    # Pokreće se svaka 3 dana (u 00:00)
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Omogućava ti da pokreneš ručno ako želiš testirati

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Blogs Table
        run: |
          curl -i -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/blogs?select=id" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Range: 0-0"
          