name: Supabase Keep Alive

on:
  schedule:
    # Izvršava se svaka 3 dana u 07:00 ujutro
    - cron: '0 7 */3 * *'
  workflow_dispatch: # Omogućava ti da pokreneš ručno kad god želiš

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Pozovi Supabase RPC Funkciju
        run: |
          curl -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/rpc/insert_random_log" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"